module.exports.descriptors = [
    "Forest",
    "Ancient",
    "Petrified",
    "Roaring",
    "Cascade",
    "Silent",
    "Dusty",
    "Sky",
    "Redwood",
    "Misty",
    "Ocean",
    "Sea",
    "Hidden",
    "Summit",
    "Maple",
    "Elk",
    "Grizzly",
    "Tumbling",
    "Cliffside",
    "Sandy",
    "Bullfrog"
];

module.exports.places = [
    "Flats",
    "Village",
    "Canyon",
    "Pond",
    "Group Camp",
    "Horse Camp",
    "Ghost Town",
    "Camp",
    "Dispersed Camp",
    "Backcountry",
    "River",
    "Creek",
    "Bay",
    "Spring",
    "Bayshore",
    "Sands",
    "Mule Camp",
    "Hunting Camp",
    "Cliffs",
    "Hollow"
];
